<a href="https://colab.research.google.com/github/muneer-ahmad10/Natural-Language-processing/blob/main/Day_07_Practice_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
corpus = [
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [4]:
v=TfidfVectorizer()
trans_output=v.fit_transform(corpus)
print(v.vocabulary_)

{'thor': 25, 'eating': 10, 'pizza': 22, 'loki': 17, 'is': 16, 'ironman': 15, 'ate': 7, 'already': 0, 'apple': 5, 'announcing': 4, 'new': 20, 'iphone': 14, 'tomorrow': 26, 'tesla': 24, 'model': 19, 'google': 12, 'pixel': 21, 'microsoft': 18, 'surface': 23, 'amazon': 2, 'eco': 11, 'dot': 9, 'am': 1, 'biryani': 8, 'and': 3, 'you': 27, 'are': 6, 'grapes': 13}

In [6]:
print(dir(v))

['_CountVectorizer__metadata_request__fit', '_CountVectorizer__metadata_request__transform', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__str__', '__subclasshook__', '__weakref__', '_build_request_for_signature', '_char_ngrams', '_char_wb_ngrams', '_check_feature_names', '_check_n_features', '_check_params', '_check_stop_words_consistency', '_check_vocabulary', '_count_vocab', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_get_default_requests', '_get_doc_link', '_get_metadata_request', '_get_param_names', '_get_tags', '_limit_features', '_more_tags', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_sort_features', '_stop_words_id', '_tfidf', '_validate_data', '_validate_ngram_range', '_validate_params', '_validate_vocabulary', '_warn_for_unused_params', '_white_spaces', '_word_ngrams', 'analyzer', 'binary', 'build_analyzer', 'build_preprocessor', 'build_tokenizer', 'decode', 'decode_error', 'dtype', 'encoding', 'fit', 'fit_transform', 'fixed_vocabulary_', 'get_feature_names_out', 'get_metadata_routing', 'get_params', 'get_stop_words', 'idf_', 'input', 'inverse_transform', 'lowercase', 'max_df', 'max_features', 'min_df', 'ngram_range', 'norm', 'preprocessor', 'set_params', 'smooth_idf', 'stop_words', 'strip_accents', 'sublinear_tf', 'token_pattern', 'tokenizer', 'transform', 'use_idf', 'vocabulary', 'vocabulary_']

In [11]:
all_feature_name=v.get_feature_names_out()

for word in all_feature_name:
  idx=v.vocabulary_.get(word)
  idf_score = v.idf_[idx]
  print(f'{word} : {idf_score}')

already : 2.386294361119891
am : 2.386294361119891
amazon : 2.386294361119891
and : 2.386294361119891
announcing : 1.2876820724517808
apple : 2.386294361119891
are : 2.386294361119891
ate : 2.386294361119891
biryani : 2.386294361119891
dot : 2.386294361119891
eating : 1.9808292530117262
eco : 2.386294361119891
google : 2.386294361119891
grapes : 2.386294361119891
iphone : 2.386294361119891
ironman : 2.386294361119891
is : 1.1335313926245225
loki : 2.386294361119891
microsoft : 2.386294361119891
model : 2.386294361119891
new : 1.2876820724517808
pixel : 2.386294361119891
pizza : 2.386294361119891
surface : 2.386294361119891
tesla : 2.386294361119891
thor : 2.386294361119891
tomorrow : 1.2876820724517808
you : 2.386294361119891

In [12]:
corpus[:2]

['Thor eating pizza, Loki is eating pizza, Ironman ate pizza already',
 'Apple is announcing new iphone tomorrow']

In [14]:
trans_output[:2].toarray()

array([[0.24266547, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24266547, 0.        , 0.        ,
        0.40286636, 0.        , 0.        , 0.        , 0.        ,
        0.24266547, 0.11527033, 0.24266547, 0.        , 0.        ,
        0.        , 0.        , 0.72799642, 0.        , 0.        ,
        0.24266547, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.30652086,
        0.5680354 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5680354 ,
        0.        , 0.26982671, 0.        , 0.        , 0.        ,
        0.30652086, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30652086, 0.        ]])

## **Problem Statement**: Given a description about a product sold on e-commerce website, classify it in one of the 4 categories
**Dataset Credits**: https://www.kaggle.com/datasets/saurabhshahane/ecommerce-text-classification

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [121]:
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

from sklearn.naive_bayes import MultinomialNB

from sklearn.ensemble import RandomForestClassifier

In [82]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/NLP/DataSets/ecommerceDataset.csv",names=["Category","Text"])

In [83]:
df.head(5)

    Category                                               Text
0  Household  Paper Plane Design Framed Wall Hanging Motivat...
1  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3  Household  SAF Flower Print Framed Painting (Synthetic, 1...
4  Household  Incredible Gifts India Wooden Happy Birthday U...

In [84]:
df.columns

Index(['Category', 'Text'], dtype='object')

In [85]:
df['Category_num']=df['Category'].map({
   'Household' : 0,
   'Books' : 1,
   'Electronics' : 2,
   'Clothing & Accessories' : 3

})

In [86]:
df['Category'].value_counts()

Category
Household                 19313
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64

balancing Dataset using undersampling

In [87]:
df_household=df[df['Category'] == 'Household'].sample(8000)
df_Books=df[df['Category'] == 'Books'].sample(8000)
df_Electronics=df[df['Category'] == 'Electronics'].sample(8000)
df_Accessories=df[df['Category'] == 'Clothing & Accessories'].sample(8000)

In [88]:
df=pd.concat([df_household,df_Books,df_Electronics,df_Accessories],axis=0)
df = df.reset_index(drop=True)

In [89]:
df.Category.value_counts()

Category
Household                 8000
Books                     8000
Electronics               8000
Clothing & Accessories    8000
Name: count, dtype: int64

In [90]:
df.head(5)

    Category                                               Text  Category_num
0  Household  Pigeon Gas Lighter with Free Knife (Set of 2) ...             0
1  Household  Honeywell Air Touch HCMF25M0012 Compound Filte...             0
2  Household  Nova NSG 2449 1000 Watt Panini Sandwich Grill ...             0
3  Household  Hope Smile Mini Portable USB Rechargeable Elec...             0
4  Household  Zollyss Toilet Brush 2 Pcs Set (Color May Vary...             0

In [91]:
df.sample(5)

                     Category  ... Category_num
11839                   Books  ...            1
25145  Clothing & Accessories  ...            3
23617             Electronics  ...            2
23279             Electronics  ...            2
22083             Electronics  ...            2

[5 rows x 3 columns]

In [102]:
df.isna().sum()

Category        0
Text            1
Category_num    0
dtype: int64

In [106]:
df=df.dropna()

In [107]:
X=df['Text']
y=df['Category_num']

# **Train_test_split**

In [108]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=2000,stratify=df.Category_num)

In [109]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (23999,)
Shape of X_test:  (8000,)

In [110]:
y_train.value_counts()

Category_num
2    6000
1    6000
0    6000
3    5999
Name: count, dtype: int64

### **using sklearn pipeline module create a classification pipeline to classify the Ecommerce Data.**

use TF-IDF for pre-processing the text.

use KNN as the classifier

print the classification report.

In [111]:



clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('KNN', KNeighborsClassifier())
])

clf.fit(X_train, y_train)


y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.94      0.94      2000
           1       0.97      0.95      0.96      2000
           2       0.95      0.95      0.95      2000
           3       0.97      0.98      0.97      2000

    accuracy                           0.96      8000
   macro avg       0.96      0.96      0.96      8000
weighted avg       0.96      0.96      0.96      8000

In [116]:
X_test[20:25]

25046    Bold N Elegant Women's Half Sleeve Cute Sneak ...
15955    Nike Polyester Red Skateboarding Icon Backpack...
26307    Lenity Girls Printed Cotton Camisole Slips/Ves...
25147    Zombom Women's Western Top Latest Western Wear...
16195    Samsung Galaxy Tab A 7.0 Tablet (7 inch, 8GB, ...
Name: Text, dtype: object

In [117]:
y_test[20:25]

25046    3
15955    1
26307    3
25147    3
16195    2
Name: Category_num, dtype: int64

In [118]:
y_pred[20:25]

array([3, 2, 3, 3, 2])

### **using sklearn pipeline module create a classification pipeline to classify the Ecommerce Data.**

use TF-IDF for pre-processing the text.

use MultinomialNB as the classifier.

print the classification report.

In [120]:
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('Multi NB', MultinomialNB())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.94      0.93      2000
           1       0.97      0.93      0.95      2000
           2       0.95      0.95      0.95      2000
           3       0.97      0.98      0.97      2000

    accuracy                           0.95      8000
   macro avg       0.95      0.95      0.95      8000
weighted avg       0.95      0.95      0.95      8000

### **using sklearn pipeline module create a classification pipeline to classify the Ecommerce Data.**


use TF-IDF for pre-processing the text.

use Random Forest as the classifier.

print the classification report.

In [ ]:

clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('Random Forest', RandomForestClassifier())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

# **Using text pre-processing to remove stop words, punctuations and apply lemmatization**

In [123]:

import spacy

nlp = spacy.load("en_core_web_sm")

def preprocess(text):

    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)

    return " ".join(filtered_tokens)

In [124]:
df['preprocessed_txt'] = df['Text'].apply(preprocess)

In [125]:
df.head()

    Category  ...                                   preprocessed_txt
0  Household  ...  Pigeon Gas Lighter Free Knife Set 2 pigeon gas...
1  Household  ...  Honeywell Air Touch HCMF25M0012 Compound Filte...
2  Household  ...  Nova NSG 2449 1000 Watt Panini Sandwich Grill ...
3  Household  ...  Hope Smile Mini Portable usb Rechargeable Elec...
4  Household  ...  Zollyss Toilet Brush 2 Pcs Set Color Vary busy...

[5 rows x 4 columns]

In [126]:
df.Text[0]

'Pigeon Gas Lighter with Free Knife (Set of 2) Pigeon gas lighter. Product si of set of two. Gas lighter from trusted brand.'

In [127]:
df.preprocessed_txt[0]

'Pigeon Gas Lighter Free Knife Set 2 pigeon gas light product si set gas lighter trusted brand'

In [129]:
X_train, X_test, y_train, y_test = train_test_split(
    df.preprocessed_txt,
    df.Category_num	,
    test_size=0.2,
    random_state=2022,
    stratify=df.Category_num
)

In [130]:
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('Random Forest', RandomForestClassifier())
])


clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)



print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94      1600
           1       0.98      0.96      0.97      1600
           2       0.98      0.95      0.97      1600
           3       0.98      0.99      0.98      1600

    accuracy                           0.96      6400
   macro avg       0.97      0.96      0.96      6400
weighted avg       0.97      0.96      0.96      6400