<a href="https://colab.research.google.com/github/muneer-ahmad10/Natural-Language-processing/blob/main/News_text_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 53.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [3]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [5]:
great=wv['great']

In [13]:
great.shape

(300,)

In [9]:
good=wv['good']

In [12]:
good.shape

(300,)

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/NLP/DataSets/fake_and_real_news.csv')

In [16]:
df.head(5)

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [21]:
df.shape

(9900, 3)

In [18]:
df.label.value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [19]:
#transforming labels column

df['trans_label']=df.label.map({
    'Fake' : 0,
    'Real' :1
})

In [20]:
df.head()

                                                Text label  trans_label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake            0
1  U.S. conservative leader optimistic of common ...  Real            1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real            1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake            0
4  Democrats say Trump agrees to work on immigrat...  Real            1

In [25]:
!python -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 844.3 kB/s eta 0:00:00
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [26]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [44]:
#preprocess and VEctorize Text


def preprocess_and_vect(text):
  doc=nlp(text)

  filtered_text=[]

  for token in doc:
    if token.is_punct or token.is_stop:
      continue
    filtered_text.append(token.lemma_)

  return wv.get_mean_vector(filtered_text)

In [49]:
# total mean of setencnce is taken in this vectorization which is called sentence tokenization
v=preprocess_and_vect("Top Tru Surrogate BRUTALLY Stabs Him In The")
v.shape

(300,)

In [50]:
df['text_vect']=df.Text.apply(lambda text :preprocess_and_vect(text))

In [51]:
df.head()

,Text,label,trans_label,text_vect
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,0,"[0.0085234195, 0.019263458, -0.010577418, 0.03..."
1,U.S. conservative leader optimistic of common ...,Real,1,"[0.00861828, 0.007408227, 0.0007675802, 0.0138..."
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,1,"[0.01793007, 0.006029178, -0.0054984074, 0.038..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,0,"[0.0124946935, 0.0121258395, -0.00019833064, 0..."
4,Democrats say Trump agrees to work on immigrat...,Real,1,"[-0.002259819, 0.01164962, 0.0036556108, 0.028..."

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(
    df.text_vect.values,
    df.trans_label,
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df.trans_label)

In [56]:
X_train

array([array([-2.81406008e-03,  6.87619392e-03,  3.39423376e-03,  3.95360738e-02,
              -1.36175575e-02, -8.13308824e-03,  3.21084671e-02, -3.23449001e-02,
               1.68617796e-02,  2.29651965e-02, -2.43959669e-02, -3.76296826e-02,
              -6.46119332e-03,  1.64720993e-02, -2.45438758e-02,  4.68500890e-02,
               5.70145063e-03,  2.61194576e-02,  4.22870228e-03, -3.21864001e-02,
               4.29314002e-03,  1.92054529e-02,  4.24828455e-02, -2.57277768e-03,
               2.06844565e-02,  3.26823303e-03, -2.66888309e-02, -1.15901825e-03,
               6.50059246e-03, -2.36961502e-03, -1.50975427e-02, -2.89285003e-04,
              -2.67314240e-02,  4.53402427e-05, -1.12956632e-02, -1.66448709e-02,
               1.39644267e-02,  2.36211065e-03, -4.24514618e-03,  3.43926027e-02,
               5.00894291e-03, -1.51310461e-02,  4.37048376e-02,  1.11676650e-02,
              -4.91475128e-03, -1.57708433e-02, -2.10426785e-02,  9.78141464e-03,
              -1.25600677e-02,  3.20965126e-02, -1.25541473e-02,  2.69360971e-02,
              -4.93882457e-03, -4.56501823e-03,  3.04846140e-03,  7.12802692e-04,
              -1.12886708e-02, -2.77648065e-02, -9.02390294e-03, -2.95280982e-02,
               6.50116801e-03,  2.94479281e-02, -2.74591725e-02, -2.39625969e-03,
               1.83411203e-02, -1.52410641e-02, -2.03626510e-02, -7.89964385e-03,
              -3.73535813e-03,  2.24055871e-02,  1.17877685e-02,  2.74414872e-03,
               2.81615034e-02,  2.37366906e-03, -2.27661394e-02, -2.53748577e-02,
               8.30142386e-03,  1.77516434e-02,  2.15477068e-02,  3.04526705e-02,
              -1.49405524e-02, -2.02871989e-02,  1.19839879e-02, -6.08834065e-03,
              -9.52695962e-03, -2.70266104e-02, -3.27461660e-02,  5.35931140e-02,
               8.25163617e-04,  4.56251903e-03,  5.18735033e-03, -1.13955373e-02,
              -4.48139869e-02, -2.09904704e-02, -8.62097833e-03, -3.32614407e-02,
               1.80786289e-02,  1.64134093e-02,  1.92082003e-02, -1.61223616e-02,
              -1.97316147e-02, -2.00225823e-02,  4.20853402e-03,  9.77153308e-04,
              -1.84037648e-02, -5.18497871e-03,  8.72567471e-04, -2.89161522e-02,
              -3.83642805e-03, -1.79183576e-02, -2.74548400e-02, -2.30954010e-02,
               3.82527336e-03, -4.14851168e-03,  3.15052643e-02, -7.56170461e-03,
               2.14046445e-02, -2.55119409e-02,  2.43885387e-02,  8.91682133e-03,
              -2.49527078e-02, -6.10882125e-04, -1.23839406e-02,  3.24645117e-02,
              -8.97468720e-03, -9.91850533e-03, -1.86050832e-02, -1.45492647e-02,
               2.41681840e-03,  1.18904402e-02, -1.41618270e-02, -1.12716425e-02,
              -9.41463187e-03,  2.62480020e-03, -1.20782375e-03,  8.41818983e-04,
               4.79184964e-04,  9.87359229e-03,  1.67982578e-02,  2.14349069e-02,
               1.77154504e-02, -3.24810818e-02, -3.43072461e-04, -2.30178069e-02,
               7.28481961e-03,  1.90783665e-02, -2.13066931e-03, -1.92064848e-02,
              -2.20126733e-02, -9.88989230e-03,  2.89303046e-02,  2.92411936e-03,
              -1.78368483e-02,  1.00970650e-02, -1.06886234e-02, -2.01922935e-02,
              -1.90016460e-02, -1.98672544e-02, -3.13132182e-02, -1.98866450e-03,
              -9.71984398e-03,  1.42946132e-02,  2.46612430e-02,  2.56639416e-03,
               3.53980879e-03, -3.68783213e-02,  3.32297496e-02, -2.84712203e-02,
               1.62970591e-02,  1.39201796e-02, -4.63920645e-02, -1.50809446e-02,
               3.83647718e-03, -3.72347571e-02, -2.29465738e-02,  1.30805443e-03,
               4.85730059e-02, -1.08654657e-02, -1.86551567e-02,  1.55943714e-03,
              -3.83525193e-02, -3.26573290e-02,  1.45275088e-03,  1.18240749e-03,
               6.53813500e-03, -2.12852359e-02,  2.62862025e-03,  7.17642019e-03,
               8.29847436e-03,  1.24647506e-02,  1.41588040e-02,  1.02527402e-02,
               1.43584237e-02, -3.72938765e-03, -1.52739836e-02,  2.04178654e-02,
              -2.90419627e-03, -1.52552435e-02, -1.09339766e-02, -3.68830115e-02,
              -4.95131593e-03,  1.85252000e-02, -3.40973251e-02, -1.67336911e-02,
               5.47105679e-03, -8.48021545e-03, -1.14300894e-02,  2.83112773e-03,
              -1.21721672e-02, -1.41266473e-02, -1.88864730e-02,  2.46806126e-02,
              -1.28772557e-02,  1.60532445e-02, -2.16912143e-02,  1.21367984e-02,
               2.01988462e-02,  9.79538076e-03, -1.60866473e-02, -6.09609485e-03,
              -2.17779540e-03,  6.79562008e-03, -7.50076678e-03, -1.16815849e-03,
               1.76545307e-02, -1.70544945e-02,  2.43063644e-02,  1.60499904e-02,
               1.71913411e-02, -1.37621397e-03,  3.91767221e-03, -2.68593784e-02,
              -1.97115988e-02,  8.85599758e-03,  3.24454866e-02, -1.03777833e-02,
               3.97590687e-03, -1.49829937e-02,  2.12797672e-02, -5.10521047e-03,
               2.29971893e-02, -1.62068345e-02, -5.80431707e-03, -2.29442082e-02,
               8.73795152e-03,  1.63131412e-02, -3.39952006e-04,  2.02359855e-02,
              -5.55884908e-04, -1.92645900e-02, -7.08619086e-03,  5.52073866e-03,
               3.01583037e-02,  1.59794614e-02,  1.72893181e-02, -2.38469392e-02,
               8.08280252e-04, -4.55226749e-03, -2.46009901e-02, -2.33786311e-02,
              -1.01810824e-02,  8.47345311e-03, -3.22429016e-02,  1.53548736e-02,
               1.58010684e-02,  2.75683552e-02, -2.85125729e-02,  1.69519894e-03,
              -3.12513299e-02, -1.28291715e-02,  2.52712681e-03,  4.95385379e-02,
               3.69691849e-02, -1.08548743e-03,  2.37245318e-02, -1.60889234e-02,
              -7.41368253e-03, -3.38954292e-02, -2.02527326e-02, -5.60389366e-03,
               6.58039143e-03, -6.69798674e-03,  7.37744244e-03,  2.16982849e-02,
              -7.61008821e-03, -1.18815862e-02, -4.07491550e-02,  1.89214926e-02,
              -1.10899215e-03,  1.52118728e-02, -1.41772889e-02,  1.72339485e-03,
              -3.16459015e-02,  6.08099764e-03, -4.01739776e-03, -3.17804776e-02,
              -1.58044603e-03, -1.28854318e-02,  7.18124816e-03, -7.76810944e-03],
             dtype=float32)                                                       ,
       array([ 7.40770809e-03,  3.33923940e-03, -1.73194408e-02,  2.53530741e-02,
              -2.37447582e-02, -1.07460283e-02,  1.29910680e-02, -2.03855727e-02,
               3.27965356e-02,  3.37703200e-03, -1.71258524e-02, -2.34663226e-02,
              -6.91226218e-03,  1.70093365e-02, -4.58564907e-02,  2.82412991e-02,
               2.63021253e-02,  3.46590541e-02, -4.07156767e-03, -3.44276279e-02,
              -3.42047075e-04,  3.52422930e-02,  2.20255144e-02, -6.59729529e-04,
               7.13739824e-03, -2.47586519e-03, -1.77565403e-02,  5.20685874e-03,
               8.93999822e-03, -2.22013192e-03, -7.62191415e-03,  1.68703292e-02,
              -3.45864631e-02, -8.02864600e-03,  1.45929074e-02, -9.11107101e-03,
               2.88324524e-02,  1.17147379e-02,  1.39491213e-02,  2.16588117e-02,
               2.12183632e-02, -1.30857956e-02,  3.32901552e-02,  9.27242171e-03,
              -2.78313681e-02, -1.35816522e-02, -1.28395734e-02, -5.37800649e-03,
               8.85647431e-04,  3.25843841e-02, -6.20608358e-03,  2.27205120e-02,
              -9.61042847e-03, -5.81535860e-04,  2.19325684e-02,  9.78994556e-03,
              -1.80998873e-02, -2.42020711e-02, -5.14324522e-03, -4.56950814e-02,
               1.28568700e-02,  1.42180808e-02, -3.39175165e-02, -1.53366094e-02,
               1.54980016e-03, -1.41854910e-02, -2.95926649e-02,  2.89687812e-02,
              -8.95852037e-03,  2.18854249e-02,  1.39053846e-02, -1.58508599e-03,
               3.28027457e-02, -3.04429187e-03, -3.69911119e-02, -1.04003204e-02,
               2.61141751e-02,  1.73985437e-02,  2.18722913e-02,  3.45286839e-02,
              -8.97067040e-03, -1.95447262e-02,  1.31847644e-02, -1.82239898e-03,
              -1.84202450e-03, -1.93341207e-02, -4.05486077e-02,  4.51151505e-02,
               1.31048716e-03, -4.78901900e-03,  4.20700107e-03, -2.38683377e-03,
              -3.00517976e-02, -3.03613469e-02, -2.81354343e-03, -2.68214177e-02,
               2.28190776e-02,  2.83540785e-02,  7.55739119e-03, -2.06860323e-02,
              -2.74912324e-02, -8.15575197e-03, -1.22189836e-03,  1.08552147e-02,
              -4.35275072e-03, -1.19585209e-02,  9.85424221e-03, -3.19378413e-02,
              -1.96800032e-03, -2.03108452e-02, -2.58716904e-02, -8.89696926e-03,
               2.37963359e-05, -5.34519320e-03,  3.19992118e-02, -1.57634390e-03,
               1.72153525e-02, -1.67592391e-02,  3.08105648e-02,  4.55284212e-03,
              -1.52876992e-02, -2.18186853e-03, -2.34768614e-02,  2.41555795e-02,
               3.93224834e-03, -1.64645985e-02, -2.60510854e-02, -1.52860824e-02,
               5.28882258e-03, -5.14480053e-03, -8.55617784e-03, -4.89408970e-02,
               3.74538405e-03,  1.84434035e-03, -7.79365562e-03, -1.76400132e-02,
               9.64865088e-04,  2.06218269e-02,  1.34225411e-03,  1.62653606e-02,
               2.96830144e-02, -2.05867328e-02, -3.95791791e-03, -3.80635262e-03,
               7.56128598e-03,  1.01033328e-02,  3.19248764e-03, -2.47700270e-02,
              -1.55257639e-02, -8.18008184e-03,  3.39406542e-02,  9.33035649e-03,
               3.02683003e-03,  5.33158099e-03, -1.21403318e-02, -3.70871578e-03,
              -1.30989756e-02, -1.38183162e-02, -2.27377191e-02, -1.73253380e-02,
              -2.12530908e-03,  1.89162623e-02,  2.10062917e-02,  2.52567586e-02,
               9.34328325e-03, -5.02124429e-02,  2.07045637e-02, -2.84047015e-02,
               1.69682410e-02,  9.29086935e-03, -2.50798203e-02, -7.83641730e-03,
               1.01368511e-02, -3.90995517e-02, -8.31469335e-03, -8.52897589e-04,
               4.01955657e-02, -2.84411218e-02, -2.08064280e-02,  3.72399250e-03,
              -3.27222571e-02, -1.66668799e-02,  1.40997926e-02,  6.73040887e-03,
              -7.87294377e-03, -1.35806259e-02, -1.10383267e-02, -2.11766735e-03,
               2.24671103e-02,  1.97470225e-02,  1.23400223e-02,  1.46585135e-02,
               2.72828750e-02,  8.05260241e-03, -9.57874488e-03,  3.02614266e-04,
               5.49695361e-03, -3.64365312e-03, -1.08457319e-02, -2.30764765e-02,
               1.30677689e-02,  1.12738591e-02, -1.63962822e-02, -4.68082819e-03,
               1.48440311e-02, -9.88891535e-03, -2.97133997e-03,  1.35230403e-02,
              -4.88524558e-03,  5.23656607e-03, -4.42736689e-03,  2.58067958e-02,
              -8.79861764e-04,  1.10679567e-02, -2.56516617e-02,  1.06893232e-04,
               1.82125606e-02,  2.51619145e-04, -2.59041525e-02, -2.17503756e-02,
              -1.81317106e-02,  9.78467707e-03, -5.58732729e-03, -1.99708831e-03,
               2.74614878e-02,  9.34121897e-04,  1.68634355e-02,  1.08017530e-02,
               1.04105016e-02,  2.26277020e-03, -2.32429265e-05, -8.59588850e-03,
              -1.94689855e-02,  3.73099791e-03,  4.08301465e-02, -9.95785347e-04,
               1.17893703e-02, -3.29446271e-02,  3.39075550e-02,  6.55072555e-03,
               6.20489754e-03, -1.63837597e-02,  2.23546359e-03, -3.61882634e-02,
               3.27572547e-04,  1.55908186e-02,  1.46247481e-03,  4.43246067e-02,
               1.09531740e-02, -2.01211665e-02,  6.02009241e-03,  2.51155980e-02,
               1.34773413e-02,  2.11448576e-02,  2.13028025e-02, -7.45790033e-03,
               1.53126400e-02,  1.27510997e-02, -1.37436874e-02, -2.88591441e-02,
              -5.39842993e-03,  4.52797720e-03, -8.85578152e-03,  7.61500234e-03,
               7.66266137e-03,  4.02905867e-02, -1.86448954e-02, -4.12004476e-04,
              -2.11167708e-02, -8.67793802e-03,  9.61105712e-03,  2.68638451e-02,
               4.19969708e-02,  1.65776443e-02,  2.38241851e-02, -1.23469876e-02,
              -1.63119435e-02, -3.69703658e-02, -1.91582479e-02, -6.73787901e-03,
              -1.08735741e-03,  5.45803644e-03,  1.38294306e-02,  2.11893432e-02,
              -5.69478609e-03, -4.97774221e-03, -1.83414072e-02,  2.00194912e-03,
               1.95320938e-02,  1.52523136e-02, -6.01635454e-03,  1.42518980e-02,
              -2.86802091e-02, -1.00654736e-02, -1.67143566e-03, -1.88926309e-02,
               1.43197663e-02, -3.39312181e-02,  1.32617252e-02,  2.80478201e-03],
             dtype=float32)                                                       ,
       array([ 1.25185344e-02,  2.05708742e-02, -5.43064065e-03,  3.18073779e-02,
              -1.80227086e-02, -8.99977982e-03,  3.12208794e-02, -1.51287764e-02,
               3.69233303e-02,  1.91443320e-02, -2.37308741e-02, -3.31486873e-02,
              -1.23386215e-02,  2.11712867e-02, -3.84442918e-02,  4.07964624e-02,
               2.76075117e-02,  3.78405042e-02,  6.86708838e-03, -3.52273993e-02,
              -1.59134751e-03,  1.97352264e-02,  4.02546115e-02,  1.54060591e-02,
               2.78561600e-02,  6.02572970e-03, -2.55814809e-02, -8.62633315e-05,
               1.90159921e-02, -1.00674406e-02, -2.43794434e-02,  1.42947314e-02,
              -3.02662961e-02, -1.44054480e-02,  6.01659529e-03,  3.80033697e-03,
               1.83683429e-02,  1.31944334e-02,  4.42091469e-03,  3.08405496e-02,
               3.30260769e-02, -2.83007380e-02,  5.40987588e-02,  2.51263031e-03,
              -2.37503946e-02, -5.89221856e-03, -5.19457273e-03, -9.07776318e-03,
               1.86482421e-03,  2.79431995e-02, -2.07021125e-02,  3.24201770e-02,
              -1.74684506e-02, -1.66300479e-02,  2.58630578e-04,  4.70857043e-03,
              -8.70790239e-03, -3.63632776e-02,  1.47474492e-02, -3.51137333e-02,
               1.23941265e-02,  2.52388529e-02, -2.72024851e-02, -2.34648418e-02,
               1.49051491e-02, -1.36377392e-02, -1.85340308e-02,  2.42084935e-02,
              -2.45911870e-02,  1.78113598e-02,  2.01303661e-02,  1.33925554e-04,
               4.36607115e-02, -3.27311980e-04, -2.57547796e-02, -2.84949094e-02,
               2.38875505e-02,  2.57264134e-02,  2.75896490e-02,  3.97874974e-02,
              -4.63784439e-03, -1.34127038e-02,  1.27261244e-02, -1.28255403e-02,
              -2.04663421e-03, -2.00054254e-02, -1.84090249e-02,  4.02561165e-02,
              -7.70943239e-03, -1.50999390e-02,  7.18679838e-03,  1.30839711e-02,
              -3.99169177e-02, -2.36776788e-02,  3.48688103e-03, -2.92171780e-02,
               1.86041761e-02,  1.89995244e-02,  1.23712979e-02, -7.35509023e-03,
              -2.03558654e-02, -2.39716955e-02,  1.31515637e-02,  2.83240038e-03,
              -2.73391954e-03, -1.66398212e-02, -4.00539674e-03, -2.59814728e-02,
               9.44970362e-03, -2.65480708e-02, -1.32466229e-02, -1.43888881e-02,
              -1.18377283e-02,  4.77049127e-03,  4.32457402e-02, -1.15459068e-02,
               3.08084339e-02, -8.38212483e-03,  2.98019201e-02,  1.71205252e-02,
              -3.49017344e-02, -2.29827710e-03, -1.39801446e-02,  2.73652989e-02,
              -1.63853858e-02, -1.76579673e-02, -2.26536915e-02, -8.70534964e-03,
              -9.14423203e-04, -2.33326037e-03, -2.40830518e-02, -4.17337641e-02,
              -8.99943430e-03,  9.12192743e-03, -9.31527372e-03, -2.12537758e-02,
               9.85365268e-03,  2.26386841e-02, -4.67821956e-04,  2.02360488e-02,
               2.95614190e-02, -3.30808051e-02,  1.08676497e-02, -1.29272952e-03,
               2.18888037e-02,  1.95429642e-02, -1.29320016e-02, -2.12936606e-02,
              -1.65013329e-03, -3.82741634e-03,  2.41485462e-02,  3.87466559e-03,
              -1.99943110e-02, -3.60725797e-03, -1.19763827e-02,  4.63740574e-03,
              -7.20364554e-03, -4.21450809e-02, -2.48992778e-02,  5.71623072e-03,
              -5.41063212e-03,  1.60708576e-02,  2.42090952e-02, -4.49011801e-03,
               1.19863078e-02, -5.13891801e-02,  3.01514231e-02, -2.83737574e-02,
               3.32625061e-02,  8.00297596e-03, -3.33598331e-02, -1.05808089e-02,
              -2.26238789e-03, -3.59139591e-02, -1.42511632e-02, -2.85465794e-04,
               3.30479108e-02, -2.75023915e-02, -2.41666492e-02,  6.83955802e-03,
              -2.73952149e-02, -3.28965150e-02,  7.65099609e-03,  1.04787750e-02,
              -9.55077820e-03, -1.33247422e-02, -1.36578679e-02,  6.91799447e-03,
               2.41472460e-02,  1.24592995e-02,  2.34688278e-02,  1.75130814e-02,
               2.79510953e-02,  1.00771375e-02, -2.40303855e-02,  2.41367589e-03,
              -7.85652176e-03, -4.80613997e-03, -1.72843393e-02, -2.82359011e-02,
               1.16054469e-03,  2.69633289e-02, -2.00850051e-02, -4.73877788e-03,
               9.83838737e-03, -5.91348018e-03, -5.49138663e-03,  1.27508258e-02,
              -3.91258020e-03, -1.90884229e-02, -1.00961505e-02,  3.35547216e-02,
              -2.83154473e-03,  1.16769671e-02, -2.84075215e-02,  3.79235513e-04,
               1.60520598e-02,  2.04272033e-03, -1.22596445e-02, -1.03081707e-02,
              -1.44500099e-02,  1.51354941e-02, -1.25976391e-02, -5.24003990e-03,
               2.76763681e-02, -1.20594781e-02,  4.33529094e-02,  1.73625872e-02,
               1.72701664e-02, -2.78455787e-03,  8.15157313e-03, -1.16549758e-02,
               1.49750919e-03, -1.02155125e-02,  3.35812643e-02,  3.64418025e-03,
               6.32206490e-03, -2.94131879e-02,  3.08504011e-02,  7.58482143e-03,
               1.45306177e-02,  3.36875627e-03, -1.07662007e-02, -3.98227684e-02,
              -1.12237977e-02,  1.02640558e-02,  1.33245829e-02,  3.76781113e-02,
               3.34918033e-03, -1.82048064e-02, -1.01775406e-02,  1.09400721e-02,
               1.10897757e-02,  1.87646784e-02,  2.10374147e-02, -4.01483988e-03,
               1.73169002e-02,  1.19211776e-02, -2.03310810e-02, -3.18746455e-02,
               5.34233032e-03,  4.36463580e-03, -1.30806733e-02,  1.88470613e-02,
               1.77302305e-02,  4.81747054e-02, -8.01438466e-03, -1.48244873e-02,
              -2.91655958e-02, -1.16087552e-02, -8.20837263e-03,  4.68291268e-02,
               4.01553921e-02,  5.68186631e-03,  1.24296276e-02, -2.30774619e-02,
              -2.19697319e-03, -4.37202603e-02, -5.20242704e-03,  3.35652987e-03,
               5.44732763e-03, -8.51424411e-03,  8.26859567e-03,  2.21340824e-02,
              -1.32889301e-02, -6.37392327e-03, -4.49793376e-02, -2.83489306e-03,
               1.91813929e-03,  7.59758102e-03,  2.36044684e-03,  7.63340387e-03,
              -4.10536043e-02, -6.68339373e-04, -1.76289733e-02, -2.51531545e-02,
               9.06463899e-03, -2.16930304e-02,  9.18494351e-03,  2.12472607e-03],
             dtype=float32)                                                       ,
       ...,
       array([-2.89417338e-03,  5.74195571e-03,  1.32779861e-02,  1.72082223e-02,
              -1.07075591e-02, -9.16108768e-03,  1.08126318e-02, -1.34245167e-02,
               3.89910713e-02,  7.99878221e-03, -4.27603409e-05, -1.48258423e-02,
              -8.19237344e-03,  1.33864041e-02, -5.44610098e-02,  2.43474990e-02,
               2.71390341e-02,  2.03757938e-02, -9.94960684e-03, -1.85528994e-02,
               7.19992816e-03,  5.10415761e-03,  1.02114333e-02, -1.60957559e-03,
               1.84833165e-02, -1.90995950e-02, -2.36569922e-02,  9.44686681e-03,
               3.96871520e-03,  1.58137158e-02,  1.28643056e-02, -2.55639981e-02,
              -2.36983914e-02,  1.07851289e-02, -8.44114984e-04, -7.02488655e-03,
               1.85197070e-02,  5.18335495e-03, -4.49616555e-03,  2.05518361e-02,
               7.35868048e-03, -9.17457696e-03,  3.89791243e-02,  1.07873362e-02,
              -2.22675819e-02, -3.61531675e-02, -1.96031183e-02,  1.17138419e-02,
              -2.84519047e-02,  1.78063065e-02,  5.77832945e-03, -4.76492941e-03,
              -8.77730269e-03,  7.54552381e-03, -1.88860414e-03,  1.08261527e-02,
              -3.74898650e-02, -2.01405734e-02, -9.58064105e-03, -3.65092345e-02,

In [55]:
print("Shape of X_train before reshaping: ", X_train.shape)
print("Shape of X_test before reshaping: ", X_test.shape)

Shape of X_train before reshaping:  (7920,)
Shape of X_test before reshaping:  (1980,)

In [58]:
#just to transform this into 2D
import numpy as np

X_train_2d = np.stack(X_train)
X_test_2d =  np.stack(X_test)

print("Shape of X_train after reshaping: ", X_train_2d.shape)
print("Shape of X_test after reshaping: ", X_test_2d.shape)

Shape of X_train after reshaping:  (7920, 300)
Shape of X_test after reshaping:  (1980, 300)

In [59]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report


clf = GradientBoostingClassifier()

clf.fit(X_train_2d, y_train)

y_pred = clf.predict(X_test_2d)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      1000
           1       0.97      0.99      0.98       980

    accuracy                           0.98      1980
   macro avg       0.98      0.98      0.98      1980
weighted avg       0.98      0.98      0.98      1980

In [61]:
test_news = [
    "Michigan governor denies misleading U.S. House on Flint water (Reuters) - Michigan Governor Rick Snyder denied Thursday that he had misled a U.S. House of Representatives committee last year over testimony on Flintâ€™s water crisis after lawmakers asked if his testimony had been contradicted by a witness in a court hearing. The House Oversight and Government Reform Committee wrote Snyder earlier Thursday asking him about published reports that one of his aides, Harvey Hollins, testified in a court hearing last week in Michigan that he had notified Snyder of an outbreak of Legionnairesâ€™ disease linked to the Flint water crisis in December 2015, rather than 2016 as Snyder had testified. â€œMy testimony was truthful and I stand by it,â€ Snyder told the committee in a letter, adding that his office has provided tens of thousands of pages of records to the committee and would continue to cooperate fully.  Last week, prosecutors in Michigan said Dr. Eden Wells, the stateâ€™s chief medical executive who already faced lesser charges, would become the sixth current or former official to face involuntary manslaughter charges in connection with the crisis. The charges stem from more than 80 cases of Legionnairesâ€™ disease and at least 12 deaths that were believed to be linked to the water in Flint after the city switched its source from Lake Huron to the Flint River in April 2014. Wells was among six current and former Michigan and Flint officials charged in June. The other five, including Michigan Health and Human Services Director Nick Lyon, were charged at the time with involuntary manslaughter",
    " WATCH: Fox News Host Loses Her Sh*t, Says Investigating Russia For Hacking Our Election Is Unpatriotic This woman is insane.In an incredibly disrespectful rant against President Obama and anyone else who supports investigating Russian interference in our election, Fox News host Jeanine Pirro said that anybody who is against Donald Trump is anti-American. Look, it s time to take sides,  she began.",
    " Sarah Palin Celebrates After White Man Who Pulled Gun On Black Protesters Goes Unpunished (VIDEO) Sarah Palin, one of the nigh-innumerable  deplorables  in Donald Trump s  basket,  almost outdid herself in terms of horribleness on Friday."
]

test_news_vectors = [preprocess_and_vect(n) for n in test_news]
clf.predict(test_news_vectors)

array([1, 0, 0])